CREATE TABLE ALUNO (
    ID_ALUNO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NO_ALUNO VARCHAR(255) NOT NULL,
    EMAIL_ALUNO VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    CURSO VARCHAR(255) ,
    
);

CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    NOME_USUARIO VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
)

CREATE TABLE CURSO (
    ID_CURSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    ID_ALUNO INT not null,
    FOREIGN KEY(ID_ALUNO) references ALUNO(ID_ALUNO)
)